### PR TITLE
Talk directly to snap store ➁

### PR DESCRIPTION
**Pull request by sparkiegeek**
After the previous attempt at fixing #272 was reverted in #698 the store side fixes have landed 💯, and this is ready for another attempt at landing.

### CODE REVIEW

**Comment by bartaz** [comment]
Sorry, I guess my recently merged PR caused some conflicts.

**Comment by sparkiegeek** [comment]
Thanks for the heads up @bartaz I've rebased on top of master and merged in your changes. Please pay close attention to `name-ownership` bits, I think it's ok but would appreciate another pair of :eyes:

**Comment by bartaz** [comment]
Seems to be looking good code-wise (especially that it was reviewed already in first attempt), but running this causes some issues with name ownership checks. Checks seems to fail and app gets into a crazy loop of unsuccessful attempts to verify name ownership by constant requests to store register-name API.

I'll try to debug.

**Comment by bartaz** [comment]
@sparkiegeek Seems like another problem with fetch and store API:

```
Fetch API cannot load https://dashboard.snapcraft.io/dev/api/register-name. Response for preflight is invalid (redirect)
```

**Comment by bartaz** [comment]
And sorry for another conflict. Was hoping to get yours reviewed and merged first, but seems there may be some store work still needed.

**Comment by sparkiegeek** [comment]
Thanks @bartaz I'll take another look

**Comment by sparkiegeek** [comment]
@bartaz care to take another look?

**Pull request merged**
